# Generated by Django 4.1 on 2022-10-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='prop', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='properties',
            field=models.ManyToManyField(blank=True, default=None, to='main.property'),
        ),
    ]
